### ISSUE TITLE
Fix error 404 page

### ISSUE THREAD

**Issue by e2jk** [e2jk/syncboom#83]
Calls to `request.url_rule.endpoint` in `base.html` fail as `request` has no `url_rule` when an error 404 is triggered.
Results in 
```
jinja2.exceptions.UndefinedError: 'None' has no attribute 'endpoint'
```
Bug introduced in 0939853fadc3fcab13021ec8d4249b44dad5a85f.
